### ISSUE TITLE
ERROR: no such image: docker pull ghcr.io/tommytran732/synapse:latest: invalid reference format

### ISSUE THREAD

**Issue by sendarion** [tommytran732/Synapse-Docker-Compose#1]
Hello,

when I try to run the "2. Run docker-compose run --rm -e SYNAPSE_SERVER_NAME=yourdomain.tld -e SYNAPSE_REPORT_STATS=no synapse generate", i get this error :

ERROR: no such image: docker pull ghcr.io/tommytran732/synapse:latest: invalid reference format

What can I do about that please?

**Comment by tommytran732** [comment]
Fixed
